# Generated by Django 5.2 on 2025-04-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='employee_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='o9_employee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='working_professional',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='unique_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
