# Generated by Django 5.2 on 2025-05-06 06:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon_app', '0002_participant_company_name_participant_employee_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
    ]
