# Generated by Django 5.2 on 2025-05-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon_app', '0004_alter_participant_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
