# Generated by Django 5.2 on 2025-05-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon_app', '0005_alter_participant_unique_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
