# Generated by Django 5.2 on 2025-05-07 07:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon_app', '0006_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={},
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
    ]
