# Generated by Django 5.2 on 2025-05-07 08:18

import walkathon_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon_app', '0007_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='unique_id',
            field=models.CharField(default=walkathon_app.models.generate_unique_id, editable=False, max_length=20, unique=True),
        ),
    ]
