# Generated by Django 5.2 on 2025-05-07 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon_app', '0008_alter_participant_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('email sent', 'Email Sent'), ('whatsapp sent', 'WhatsApp Sent')], max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walkathon_app.participant')),
            ],
        ),
    ]
